/**
 * PeopleOS — Employee Payroll & Payslips Page
 * Route: /employee/payroll
 *
 * Displays employee's confidential salary payslips and detailed breakdown modal.
 * Reuses existing Modal, Button, EmptyState, Loading, ErrorMessage components.
 */

import React, { useState, useEffect, useCallback } from 'react';
import Button from '../../../components/common/Button';
import Modal from '../../../components/common/Modal';
import EmptyState from '../../../components/common/EmptyState';
import ErrorMessage from '../../../components/common/ErrorMessage';
import Loading from '../../../components/common/Loading';
import {
  getPayslips,
  getPayslipById,
} from '../../../services/employee/employeePortalService';
import '../employee.css';

const EmployeePayrollPage = () => {
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Selected Payslip Detail Modal
  const [selectedPayslip, setSelectedPayslip] = useState(null);
  const [detailLoading, setDetailLoading] = useState(false);

  const fetchPayslipData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await getPayslips();
      const list = res.data || res;
      setPayslips(Array.isArray(list) ? list : []);
    } catch (err) {
      console.error('Failed to load payslips:', err);
      setError(err.message || 'Unable to retrieve payslip records.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchPayslipData();
  }, [fetchPayslipData]);

  const handleViewPayslip = async (payslipId) => {
    setDetailLoading(true);
    try {
      const res = await getPayslipById(payslipId);
      setSelectedPayslip(res.data || res);
    } catch (err) {
      console.error('Failed to view payslip detail:', err);
    } finally {
      setDetailLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return <Loading message="Loading your payslips..." />;
  }

  if (error) {
    return <ErrorMessage message={error} onRetry={fetchPayslipData} />;
  }

  const formatDate = (isoString) => {
    if (!isoString) return '—';
    return new Date(isoString).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const renderStateBadge = (state) => {
    switch (state) {
      case 'Paid':
        return <span className="badge badge-success">Paid</span>;
      case 'Verified':
        return <span className="badge badge-info">Verified</span>;
      default:
        return <span className="badge badge-neutral">{state || 'Draft'}</span>;
    }
  };

  return (
    <div className="module-page">
      {/* ── Page Header ── */}
      <div className="page-header">
        <div>
          <h2 className="page-title">My Payroll &amp; Payslips</h2>
          <p className="page-subtitle">Access your salary payments and tax deduction statements</p>
        </div>
      </div>

      {payslips.length === 0 ? (
        <EmptyState
          title="No Payslips Available"
          description="Your payroll statements will be listed here once generated by the HR/Finance team."
        />
      ) : (
        <div className="table-container card">
          <table>
            <thead>
              <tr>
                <th>Period</th>
                <th>Payment Date</th>
                <th>Gross Salary</th>
                <th>Net Pay</th>
                <th>Status</th>
                <th style={{ textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {payslips.map((slip) => (
                <tr key={slip._id}>
                  <td>
                    <span className="font-semibold">{slip.payrun?.name || 'Monthly Payroll'}</span>
                  </td>
                  <td>{formatDate(slip.createdAt)}</td>
                  <td>${slip.grossPay?.toLocaleString()}</td>
                  <td>
                    <span className="font-semibold" style={{ color: 'var(--color-primary)' }}>
                      ${slip.netPay?.toLocaleString()}
                    </span>
                  </td>
                  <td>{renderStateBadge(slip.state)}</td>
                  <td style={{ textAlign: 'right' }}>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleViewPayslip(slip._id)}
                    >
                      View Breakdown →
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* ── Payslip Breakdown Modal ── */}
      <Modal
        isOpen={!!selectedPayslip}
        onClose={() => setSelectedPayslip(null)}
        title={selectedPayslip ? `Payslip — ${selectedPayslip.payrun?.name || 'Period Statement'}` : 'Payslip'}
      >
        {selectedPayslip && (
          <div>
            <div className="payslip-summary-header">
              <div>
                <span className="text-muted text-sm">Net Payable Salary</span>
                <div className="payslip-net-amount">${selectedPayslip.netPay?.toLocaleString()}</div>
              </div>
              <div style={{ textAlign: 'right' }}>
                <span className="text-muted text-sm">Status</span>
                <div>{renderStateBadge(selectedPayslip.state)}</div>
              </div>
            </div>

            <h4 style={{ fontSize: 'var(--font-size-sm)', fontWeight: 600, marginBottom: 10 }}>
              Salary &amp; Deduction Line Items
            </h4>

            {selectedPayslip.lines && selectedPayslip.lines.length > 0 ? (
              <div className="table-container card" style={{ marginBottom: 20 }}>
                <table>
                  <thead>
                    <tr>
                      <th>Description</th>
                      <th>Category</th>
                      <th style={{ textAlign: 'right' }}>Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {selectedPayslip.lines.map((line, idx) => (
                      <tr key={idx}>
                        <td>{line.name}</td>
                        <td>
                          <span className="badge badge-neutral">{line.category}</span>
                        </td>
                        <td
                          style={{
                            textAlign: 'right',
                            fontWeight: 600,
                            color: line.amount < 0 ? '#DC2626' : 'var(--color-text)',
                          }}
                        >
                          {line.amount < 0 ? `-$${Math.abs(line.amount).toLocaleString()}` : `$${line.amount.toLocaleString()}`}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <p className="text-muted text-sm" style={{ marginBottom: 20 }}>
                Standard monthly salary allocation.
              </p>
            )}

            <div className="modal-form-actions">
              <Button variant="secondary" onClick={handlePrint}>
                🖨️ Print / Download
              </Button>
              <Button variant="primary" onClick={() => setSelectedPayslip(null)}>
                Close
              </Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default EmployeePayrollPage;
